// leave off @2x/@3x
const images = {
  Alert: require('../Images/Alert.png'),
  BackArrow: require('../Images/BackArrow.png'),
  Contacts: require('../Images/Contacts.png'),
  ddff: require('../Images/ddff.png'),
  SelectedContacts: require('../Images/SelectedContacts.png'),
  Home: require('../Images/Home.png'),
  SelectedHome: require('../Images/SelectedHome.png'),
  renderImage1: require('../Images/renderImage1.png'),
  newprogram: require('../Images/newprogram.png'),
  renderImage2: require('../Images/renderImage2.png'),
  check: require('../Images/check.png'),
  chaudt: require('../Images/chaudt.png'),
  Indicators: require('../Images/Indicators.png'),
  explorer: require('../Images/explorer.png'),
  muscle: require('../Images/muscle.png'),
  menu: require('../Images/menu.png'),
  star: require('../Images/star.png'),
  increaseFocus: require('../Images/increaseFocus.png'),
  Boast: require('../Images/Boast.png'),
  buildMuscle: require('../Images/buildMuscle.png'),
  heart: require('../Images/heart.png'),
  account: require('../Images/account.png'),
  search: require('../Images/search.png'),
  Token: require('../Images/Token.png'),
  Arrow: require('../Images/Arrow.png'),
  selectedSearch: require('../Images/selectedSearch.png'),
  clock: require('../Images/clock.png'),
  dropdown: require('../Images/dropdown.png'),
  stars: require('../Images/stars.png'),
  bluecheck: require('../Images/bluecheck.png'),
  price: require('../Images/price.png'),
  Share: require('../Images/Share.png'),
  whiteman: require('../Images/whiteman.png'),
  message: require('../Images/message.png'),
  greenarrow: require('../Images/greenarrow.png'),
  whitecheck: require('../Images/whitecheck.png'),
}

export default images
